[WHISPER]
whisper_version_default = "faster-whisper"
openai_whisper_model_default = "large"
faster_whisper_model_default = "large"
faster_whisper_model_local = false
faster_whisper_model_local_path = ""

[KIMI]
kimi_key = "Y2"

[GPT]
openai_key = "sk-"
openai_base = "3"
