[WHISPER_LOCAL]
local = false
model_local_path = ""

[WHISPER]
whisper_model_default = "large"
whisper_version_default = "faster-whisper"

[KIMI]
kimi_key = ""

[GPT]
openai_key = "sk-"
openai_base = "3"
